### PR TITLE
Add base.hbs + wrap.hbs & helpers.

### PR DESCRIPTION
**Pull request by chrisdickinson**
This simplifies the CSS/JS/Images -- everything (static) lives in the style repo.

It also standardizes the page boilerplate.

splash

speakers

The meetup page is still unstyled, and there's more work to be done... well, pretty much everyplace, but it's a start.

### CODE REVIEW

**Comment by hackygolucky** [comment]
I'll review this more after I wake up a little this morning, but THANK YOU.

**Comment by hackygolucky** [comment]
:+1:

**Comment by dlmanning** [comment]
:+1:

**Comment by nvcexploder** [comment]
:+1:

**Pull request merged**
